'use client'

import { useCallback, useEffect, useState } from 'react'
import { Smartphone, Trash2, AlertTriangle, CheckCircle2, Clock, Loader2, Search } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import { toast } from 'sonner'
import { getDeviceBindings, removeDeviceBinding } from '@/app/superadmin/actions'

interface DeviceBinding {
  id: string
  userId: string
  userName: string
  userEmail: string
  deviceId: string
  deviceName: string
  deviceType: 'android' | 'ios' | 'web'
  appVersion: string | null
  bindDate: string
  lastUsed: string
  isActive: boolean
}

const SUPPORTED_DEVICE_TYPES = ['android', 'ios', 'web'] as const

function isSupportedDeviceType(value: string): value is DeviceBinding['deviceType'] {
  return SUPPORTED_DEVICE_TYPES.includes(value as DeviceBinding['deviceType'])
}

/**
 * Device Management Page
 * 
 * Displays all device bindings for employees. Each employee can have:
 * - 1 mobile device (Android/iOS)
 * - 1 app device (Windows/Mac/Web)
 * 
 * Device IDs are generated by the mobile/desktop apps using:
 * - Mobile apps: Device IMEI, Android ID, or iOS UDID
 * - App devices: Machine ID, hardware UUID, or generated unique identifier
 * 
 * Database Schema (device_bindings table):
 * - deviceId: Unique identifier from the mobile/app device (generated by the app)
 * - deviceName: Human-readable name (e.g., "Samsung Galaxy S23")
 * - deviceType: "mobile" or "app"
 * - appVersion: Version of the app when device was bound
 * - bindDate: When device was bound to the account
 * - lastUsed: Last login/sync timestamp (updated on each app startup)
 * - isActive: Whether the binding is currently active
 */
export default function DeviceManagementPage() {
  const [devices, setDevices] = useState<DeviceBinding[]>([])
  const [searchQuery, setSearchQuery] = useState('')
  const [selectedDeviceId, setSelectedDeviceId] = useState<string | null>(null)
  const [showConfirmDelete, setShowConfirmDelete] = useState(false)
  const [loading, setLoading] = useState(true)
  const [loadError, setLoadError] = useState(false)
  const [deleting, setDeleting] = useState(false)

  const loadDevices = useCallback(async () => {
    try {
      setLoading(true)
      setLoadError(false)
      const data = await getDeviceBindings()
      const normalizedDevices: DeviceBinding[] = data
        .filter((device) => isSupportedDeviceType(device.deviceType))
        .map((device) => ({
          ...device,
          deviceType: device.deviceType as DeviceBinding['deviceType'],
        }))
      setDevices(normalizedDevices)
    } catch (error) {
      console.error('[v0] Error loading devices:', error)
      setLoadError(true)
      toast.error('Failed to load devices')
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    const load = window.setTimeout(() => {
      void loadDevices()
    }, 0)

    return () => window.clearTimeout(load)
  }, [loadDevices])

  const normalizedSearchQuery = searchQuery.trim().toLowerCase()
  const filteredDevices = devices.filter((device) => {
    if (!normalizedSearchQuery) return true
    return [device.userName, device.userEmail, device.userId]
      .some((value) => value.toLowerCase().includes(normalizedSearchQuery))
  })

  const handleRemoveDevice = (deviceId: string) => {
    setSelectedDeviceId(deviceId)
    setShowConfirmDelete(true)
  }

  const confirmRemoveDevice = async () => {
    if (!selectedDeviceId) return

    try {
      setDeleting(true)
      const result = await removeDeviceBinding(selectedDeviceId)
      
      setDevices((prev) => prev.filter((d) => d.id !== selectedDeviceId))
      
      toast.success('Device Binding Removed', {
        description: result.message,
      })
    } catch (error) {
      console.error('[v0] Error removing device:', error)
      toast.error('Failed to remove device', {
        description: error instanceof Error ? error.message : 'An error occurred'
      })
    } finally {
      setDeleting(false)
      setShowConfirmDelete(false)
      setSelectedDeviceId(null)
    }
  }

  const activeCount = devices.filter((d) => d.isActive).length
  const inactiveCount = devices.filter((d) => !d.isActive).length

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Device Management</h1>
        <p className="text-muted-foreground mt-2">
          Manage account device bindings. Each account can have one mobile device and one app device bound for login restrictions.
        </p>
      </div>

      {/* Stats Cards */}
      <div className="grid gap-4 md:grid-cols-3">
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Total Devices</p>
                <p className="text-2xl font-bold mt-1">{devices.length}</p>
              </div>
              <div className="rounded-lg bg-primary/10 p-3">
                <Smartphone className="h-6 w-6 text-primary" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Active Devices</p>
                <p className="text-2xl font-bold mt-1 text-success">{activeCount}</p>
              </div>
              <div className="rounded-lg bg-success/10 p-3">
                <CheckCircle2 className="h-6 w-6 text-success" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Inactive Devices</p>
                <p className="text-2xl font-bold mt-1 text-warning">{inactiveCount}</p>
              </div>
              <div className="rounded-lg bg-warning/10 p-3">
                <Clock className="h-6 w-6 text-warning" />
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Search */}
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center">
        <div className="relative w-full sm:max-w-md">
          <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            value={searchQuery}
            onChange={(event) => setSearchQuery(event.target.value)}
            placeholder="Search by employee name or code"
            aria-label="Search devices by employee name or code"
            className="pl-9"
          />
        </div>
        <p className="text-sm text-muted-foreground sm:ml-auto">
          Showing {filteredDevices.length} device{filteredDevices.length !== 1 ? 's' : ''}
        </p>
      </div>

      {/* Devices List */}
      <div className="space-y-3">
        {loading ? (
          <Card>
            <CardContent className="pt-6 text-center">
              <Loader2 className="h-12 w-12 text-muted-foreground/30 mx-auto mb-3 animate-spin" />
              <p className="text-muted-foreground">Loading devices...</p>
            </CardContent>
          </Card>
      ) : loadError ? (
  <Card>
  <CardContent className="pt-6 text-center">
  <Smartphone className="h-12 w-12 text-destructive/50 mx-auto mb-3" />
  <p className="text-destructive">Unable to load devices</p>
  <p className="text-sm text-muted-foreground mt-1">Try again to retrieve the registered device bindings.</p>
  <Button variant="outline" className="mt-4" onClick={() => void loadDevices()}>Try again</Button>
  </CardContent>
  </Card>
      ) : filteredDevices.length === 0 ? (
  <Card>
            <CardContent className="pt-6 text-center">
              <Smartphone className="h-12 w-12 text-muted-foreground/30 mx-auto mb-3" />
              <p className="text-muted-foreground">
                {normalizedSearchQuery ? 'No devices match your search' : 'No devices found'}
              </p>
            </CardContent>
          </Card>
        ) : (
          filteredDevices.map((device) => (
            <Card key={device.id} className="border-border">
              <CardContent className="pt-6">
                <div className="flex items-start justify-between gap-4">
                  <div className="flex-1">
                    <div className="flex items-center gap-3 mb-3">
                      <div className="rounded-lg bg-primary/10 p-2">
                        <Smartphone className="h-5 w-5 text-primary" />
                      </div>
                      <div>
                        <h3 className="font-semibold text-foreground">{device.deviceName}</h3>
                        <p className="text-sm text-muted-foreground">
                          {device.userName} ({device.userEmail})
                        </p>
                      </div>
                    </div>

                    <div className="grid gap-2 mt-4 text-sm">
                      <div className="flex items-center justify-between">
                        <span className="text-muted-foreground">Type:</span>
                        <span className="font-medium capitalize">{device.deviceType}</span>
                      </div>
                      <div className="flex items-center justify-between">
                        <span className="text-muted-foreground">Device ID:</span>
                        <span className="font-mono text-xs">{device.deviceId}</span>
                      </div>
                      <div className="flex items-center justify-between">
                        <span className="text-muted-foreground">Bound Date:</span>
                        <span>{device.bindDate}</span>
                      </div>
                      <div className="flex items-center justify-between">
                        <span className="text-muted-foreground">Last Used:</span>
                        <span>{device.lastUsed}</span>
                      </div>
  <div className="flex items-center justify-between">
  <span className="text-muted-foreground">App Version:</span>
  <span>{device.appVersion ?? 'Not provided'}</span>
  </div>
                    </div>

                    <div className="flex items-center gap-2 mt-4">
                      {device.isActive ? (
                        <Badge className="bg-success">Active</Badge>
                      ) : (
                        <Badge variant="secondary">Inactive</Badge>
                      )}
                    </div>
                  </div>

                  <Button
                    variant="ghost"
                    size="icon"
                    className="text-destructive hover:text-destructive hover:bg-destructive/10"
                    onClick={() => handleRemoveDevice(device.id)}
                    disabled={deleting}
                  >
                    <Trash2 className="h-4 w-4" />
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))
        )}
      </div>

      {/* Alert Dialog for Confirmation */}
      <AlertDialog open={showConfirmDelete} onOpenChange={setShowConfirmDelete}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle className="flex items-center gap-2">
              <AlertTriangle className="h-5 w-5 text-warning" />
              Remove Device Binding
            </AlertDialogTitle>
            <AlertDialogDescription>
              This will remove the device binding for the selected device. The user will need to rebind their device before they can login from this device again.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <div className="my-4 p-3 bg-warning/10 rounded-lg border border-warning/30">
            <p className="text-sm font-medium text-foreground">
              Device:{' '}
              <span className="font-semibold">
                {devices.find((d) => d.id === selectedDeviceId)?.deviceName}
              </span>
            </p>
            <p className="text-sm text-muted-foreground mt-1">
              User:{' '}
              <span className="font-semibold">
                {devices.find((d) => d.id === selectedDeviceId)?.userName}
              </span>
            </p>
          </div>
          <AlertDialogCancel disabled={deleting}>Cancel</AlertDialogCancel>
          <AlertDialogAction
            onClick={confirmRemoveDevice}
            className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            disabled={deleting}
          >
            {deleting && <Loader2 className="h-4 w-4 mr-2 animate-spin" />}
            Remove Binding
          </AlertDialogAction>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  )
}
